export enum ErrorsEnum {
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  LAND_NOT_FOUND = 'LAND_NOT_FOUND',
  DONT_HAVE_PERMISSION = 'DONT_HAVE_PERMISSION',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  FILE_SMALL = 'FILE_SMALL',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  INVALID_USER_TYPE = 'INVALID_USER_TYPE',
  UPLOAD_FILES_FAILED = 'UPLOAD_FILES_FAILED',
  FILE_ALREADY_EXISTS = 'FILE_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
}